#!/bin/bash
# SPDX-FileCopyrightText: 2024-2026 Cloudflare Inc., Luke Curley, Mike English and contributors
# SPDX-FileCopyrightText: 2023-2024 Luke Curley and contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Download the Big Buck Bunny video if it doesn't exist
if [ ! -f dev/bbb.fmp4 ]; then
	if [ ! -f dev/bbb.mp4 ]; then
		echo "Downloading ya boye Big Buck Bunny..."
		wget https://bitmovin-public-amer.s3.amazonaws.com/inputs/bbb_sunflower_1080p_60fps_normal.mp4 -O dev/bbb.mp4
	fi

	echo "Converting to a (properly) fragmented MP4..."
	ffmpeg -i dev/bbb.mp4 \
		-map 0:v:0 -map 0:a:0 \
		-c:v copy -c:a aac -b:a 128k \
		-f mp4 -movflags cmaf+separate_moof+delay_moov+skip_trailer+frag_every_frame \
		dev/bbb.fmp4
fi

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Connect to localhost by default.
HOST="${HOST:-localhost}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"
SCHEME="${SCHEME:-https}"

# Use the name "bbb" for the broadcast.
NAME="${NAME:-bbb}"

# Combine the host into a URL.
URL="${URL:-"$SCHEME://$ADDR"}"

# Default to a source video
INPUT="${INPUT:-dev/bbb.fmp4}"

# Print out the watch URL
echo "Watch URL: https://quic.video/watch/$NAME?server=$ADDR"

# Run ffmpeg and pipe the output to moq-pub
ffmpeg -hide_banner -v quiet \
	-stream_loop -1 -re \
	-i "$INPUT" \
	-c copy \
	-f mp4 -movflags cmaf+separate_moof+delay_moov+skip_trailer+frag_every_frame \
	- | cargo run --bin moq-pub -- --name "$NAME" "$URL" "$@"
